name: CreateNewRepo

on:
  workflow_dispatch:
    inputs:
        new_repository_name:
            description: The name of the new DAR repository
            type: string
            required: true
  push:
    branches:
      - ondemand
env:
    GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  display-secret:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the codesss
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check for existing repo
        id: repo-check
        run: |
          ORG=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          REPO_NAME="${{ inputs.new_repository_name }}"
          echo "ORG=$ORG" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

          echo "repo_present=true" >> $GITHUB_OUTPUT
          echo "::notice::Found Repository $REPO_NAME."
          exit 0

      - name: init repo
        run: |
          gh repo create "$ORG/$REPO_NAME" --private
          echo "::notice::Created repository `$REPO_NAME`"
          # create empty main branch on the new repo

      - name: Set id for git commit
        run: |
          git config --global user.name "LSCSDE Governance Actions"
          git config --global user.email "lscsde-actions@github.com"

      - name: Initialize and push empty main branch
        run: |
          git init
          git remote add origin "https://$GH_TOKEN@github.com/$ORG/$REPO_NAME.git"
          git commit --allow-empty -m "Initial empty commit"
          git branch -M main
          git push -u origin main

      - name: Show branches
        run: |
          gh api repos/$ORG/$REPO_NAME/branches --jq '.[].name'