name: Access Organization Secrets OnDemand

on:
  workflow_dispatch:
  push:
    branches:
      - ondemand

jobs:
  display-secret:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check ou tthe code
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Access and safely output an organization-level secret
      - name: Display organization secret
        run: echo ${{secrets.SECRET1}} | sed 's/./& /g'
